# Numpy Practice by Rajdip

In [5]:
import numpy as np

In [6]:
np.__version__

'2.1.3'

In [7]:
#Numpy Creation , atrribute,methods

a=np.array([1,2,6,7,8,9,300])
print(a)

[  1   2   6   7   8   9 300]


In [8]:
b=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
c=np.array([[[1,2,3,4],
             [5,6,7,8],
             [8,9,10,11]
            ]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]]])

In [10]:
#how to change data type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [11]:
a.astype(np.int32)

array([  1,   2,   6,   7,   8,   9, 300], dtype=int32)

In [12]:
a.astype(np.int16)

array([  1,   2,   6,   7,   8,   9, 300], dtype=int16)

In [13]:
a.itemsize

8

In [14]:
b.itemsize

8

In [15]:
c.ndim

3

In [16]:
b.ndim

2

In [17]:
c.shape

(1, 3, 4)

In [18]:
b.shape

(3, 3)

In [19]:
b.reshape((3,3))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
np.random.random((2,5)) #random function 

array([[0.39117503, 0.199018  , 0.70195342, 0.7350622 , 0.99231633],
       [0.68869275, 0.54115449, 0.08849851, 0.89965445, 0.9446398 ]])

In [21]:
np.random.random((4,4))

array([[0.70013601, 0.21213233, 0.65952783, 0.40909639],
       [0.49193384, 0.76500758, 0.87940366, 0.42972096],
       [0.92194856, 0.74628953, 0.36484843, 0.67493355],
       [0.57124622, 0.48276129, 0.39621934, 0.15763338]])

In [22]:
x=np.linspace(-20,20,10)
x

array([-20.        , -15.55555556, -11.11111111,  -6.66666667,
        -2.22222222,   2.22222222,   6.66666667,  11.11111111,
        15.55555556,  20.        ])

# Recap

In [ ]:
# dtype -> check the data type of particular numpy array print(arrayname.dtype)
# astype -> we can change the data type of numpy array.We can reduce the memory space for particular array
        # -> arrayname.astype(np.int32)
# random --> np.random.random((5,5))
        # -> generates numpy array with the random numbers of 0,1
# reshape --> 
# linspace --> doesnot need tuple to put values
# arange

In [19]:
x1=np.round(np.random.random((4,5)))
print(x1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [20]:
x2=np.floor(np.random.random((4,5)))
print(x2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
x3=np.ceil(np.random.random((4,5)))
print(x3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
x3.shape

(4, 5)

In [26]:
z=np.arange(1,26,1).reshape((5,5))
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
z[[1,2],1:3]

array([[ 7,  8],
       [12, 13]])

In [28]:
z[[1,2],1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [29]:
z[[1,2],1:5]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [30]:
z[:,2]

array([ 3,  8, 13, 18, 23])

In [31]:
z[1,]

array([ 6,  7,  8,  9, 10])

In [32]:
z[[1,3],::4]

array([[ 6, 10],
       [16, 20]])

In [33]:
z.ndim

2

In [34]:
z[[3,4],2:5]

array([[18, 19, 20],
       [23, 24, 25]])

In [35]:
z[[2,4],::3]

array([[11, 14],
       [21, 24]])

In [36]:
z[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [37]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11]]])

In [38]:
c.T #Transpose is mainly used to change from row to column and from column to row in numpy array

array([[[ 1],
        [ 5],
        [ 8]],

       [[ 2],
        [ 6],
        [ 9]],

       [[ 3],
        [ 7],
        [10]],

       [[ 4],
        [ 8],
        [11]]])

In [39]:
c.ravel() #converts 2D array to 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10, 11])

In [40]:
z1=np.arange(1,11,1).reshape((2,5))
z1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
z2=np.arange(1,11,1).reshape((5,2))
z2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
np.dot(z1,z2) # Dot poroduct of two arrays

array([[ 95, 110],
       [220, 260]])

In [43]:
np.dot(z1,c) # condition is --> Column value of 1st matrix=row value of 2nd matrix
             # othrewise we will get error

ValueError: shapes (2,5) and (1,3,4) not aligned: 5 (dim 1) != 3 (dim 1)

In [44]:
print(z2.dtype)

int64


In [45]:
z2.astype(np.int32)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)

# Indexing & Slicing

In [ ]:
# ** 1,2,3 use [] inside[] --> [[1,2,3],1:3]
# ** : --> no [] and :: --> no []
# ** in case of jump then use :: 
#  11 to 14 then can write ::3 , 
# 1 to 3 --> 1:4 (4-1=3)

In [46]:
z4=np.arange(1,26).reshape((5,5))
z4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
z4[:,2] #for one column need all rows element

array([ 3,  8, 13, 18, 23])

In [48]:
z4[2,] #for one row need all columns element

array([11, 12, 13, 14, 15])

In [49]:
# 789
# 12 13 14
# 17 18 19

z4[1:4,1:4] #no jump that's why colon (:) is used

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [50]:
# 7,10 12,15
z4[[1,2],1::3] #jump from 7 to 10 --> 3 jump

array([[ 7, 10],
       [12, 15]])

# Fancy Indexing

In [51]:
#1 4 11 14 21 24
z4[[0,2,4],::3]

array([[ 1,  4],
       [11, 14],
       [21, 24]])

In [52]:
# 2 3 4 12 13 14 22 23 24
z4[[0,2,4],1:4]

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24]])

In [53]:
# # 1,3 4th col
z4[:,[1,3,4]]

array([[ 2,  4,  5],
       [ 7,  9, 10],
       [12, 14, 15],
       [17, 19, 20],
       [22, 24, 25]])

# Boolean Indexing

In [53]:
z6=np.random.random((5,5))
z6

array([[0.1036803 , 0.90076384, 0.73726451, 0.33233944, 0.0512946 ],
       [0.86390132, 0.88452843, 0.84674457, 0.33170061, 0.45871781],
       [0.54311012, 0.0325388 , 0.90198526, 0.05924245, 0.83460856],
       [0.781028  , 0.06054913, 0.46061686, 0.7224223 , 0.75284644],
       [0.8653869 , 0.7672226 , 0.88848448, 0.5115344 , 0.50928144]])

In [54]:
np.linspace(-20,30,15).reshape((5,3))

array([[-20.        , -16.42857143, -12.85714286],
       [ -9.28571429,  -5.71428571,  -2.14285714],
       [  1.42857143,   5.        ,   8.57142857],
       [ 12.14285714,  15.71428571,  19.28571429],
       [ 22.85714286,  26.42857143,  30.        ]])

In [55]:
z5=np.random.randint(1,201,20).reshape((5,4))
z5

array([[ 89, 120, 105, 121],
       [124,  20,  74,  13],
       [ 35,  72, 155,  12],
       [163, 105,  62, 139],
       [184,  31,  20,  30]], dtype=int32)

In [56]:
z5[z5%2==0] #even

array([120, 124,  20,  74,  72,  12,  62, 184,  20,  30], dtype=int32)

In [57]:
z5[z5<175]

array([ 89, 120, 105, 121, 124,  20,  74,  13,  35,  72, 155,  12, 163,
       105,  62, 139,  31,  20,  30], dtype=int32)

In [58]:
# odd & divisible with 5
z5[(z5%2!=0) & (z5%5==0)]

array([105,  35, 155, 105], dtype=int32)

In [59]:
# odd & not divisible with 5
z5[(z5%2!=0) & (z5%5!=0)]

array([ 89, 121,  13, 163, 139,  31], dtype=int32)

In [60]:
z5[z5%10!=0]

array([ 89, 105, 121, 124,  74,  13,  35,  72, 155,  12, 163, 105,  62,
       139, 184,  31], dtype=int32)

In [23]:
v1=np.random.randint(-10,15,25).reshape((5,5)) # -10 theke 15 obdi 25 ta element chai thus, (5*5)
v1

array([[10,  6, -6,  1, 12],
       [-4,  6,  5,  3, -3],
       [-3, 10,  2, -1, -9],
       [-7, -1,  0, -8,  2],
       [-1, -6,  6,  7,  9]], dtype=int32)

In [25]:
v2=np.linspace(-15,15,15).reshape((5,3))   # -15 theke 15 obdi 15 ta element chai thus, (5*3)
v2

array([[-15.        , -12.85714286, -10.71428571],
       [ -8.57142857,  -6.42857143,  -4.28571429],
       [ -2.14285714,   0.        ,   2.14285714],
       [  4.28571429,   6.42857143,   8.57142857],
       [ 10.71428571,  12.85714286,  15.        ]])

In [35]:
v3=np.arange(1,16,1).reshape((3,5)) # range() er moto 1 to 16 mane 1 to (16-1)=15, 1 step kore tai (3*5)
v3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
np.dot(v2,v3) # 1st matrix er column value = 2nd matrix er row value tai dot product hobe otherwise error hobe

array([[-210.        , -248.57142857, -287.14285714, -325.71428571,
        -364.28571429],
       [ -94.28571429, -113.57142857, -132.85714286, -152.14285714,
        -171.42857143],
       [  21.42857143,   21.42857143,   21.42857143,   21.42857143,
          21.42857143],
       [ 137.14285714,  156.42857143,  175.71428571,  195.        ,
         214.28571429],
       [ 252.85714286,  291.42857143,  330.        ,  368.57142857,
         407.14285714]])

In [38]:
v4=np.random.random((4,3))
v4

array([[0.42355502, 0.4785664 , 0.79923593],
       [0.07134318, 0.11528302, 0.29894865],
       [0.8000948 , 0.04226297, 0.20511994],
       [0.95634375, 0.48635313, 0.46514085]])

In [39]:
v1

array([[10,  6, -6,  1, 12],
       [-4,  6,  5,  3, -3],
       [-3, 10,  2, -1, -9],
       [-7, -1,  0, -8,  2],
       [-1, -6,  6,  7,  9]], dtype=int32)

In [40]:
v1[:,1:4]

array([[ 6, -6,  1],
       [ 6,  5,  3],
       [10,  2, -1],
       [-1,  0, -8],
       [-6,  6,  7]], dtype=int32)

In [41]:
v1[:,::3]

array([[10,  1],
       [-4,  3],
       [-3, -1],
       [-7, -8],
       [-1,  7]], dtype=int32)

In [42]:
v1[:,3]

array([ 1,  3, -1, -8,  7], dtype=int32)

In [43]:
v1[:,::4]

array([[10, 12],
       [-4, -3],
       [-3, -9],
       [-7,  2],
       [-1,  9]], dtype=int32)

In [44]:
# 5 3 2 -1 6 7 
v1[[1,2,4],2:4]

array([[ 5,  3],
       [ 2, -1],
       [ 6,  7]], dtype=int32)

In [45]:
# -1 -9 -8 2
v1[[2,3],3:5]

array([[-1, -9],
       [-8,  2]], dtype=int32)

In [46]:
# 10 6 -4 6 -3 10
v1[[0,1,2],0:2]

array([[10,  6],
       [-4,  6],
       [-3, 10]], dtype=int32)

In [47]:
# 6 1 10 -1 -6 7
v1[[0,2,4],1::2]

array([[ 6,  1],
       [10, -1],
       [-6,  7]], dtype=int32)

In [48]:
# -6 12 2 -9 6 9
v1[[0,2,4],2::2]

array([[-6, 12],
       [ 2, -9],
       [ 6,  9]], dtype=int32)

In [49]:
# 6 -3 -1 2
v1[[1,3],1::3]

array([[ 6, -3],
       [-1,  2]], dtype=int32)

In [50]:
v1[[1,2,4],1::3]

array([[ 6, -3],
       [10, -9],
       [-6,  9]], dtype=int32)

In [52]:
np.log(v3)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [53]:
np.exp(v3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [54]:
np.prod(v2,axis=1) # finds product of all items column wise in numpy array

array([-2066.32653061,  -236.1516035 ,    -0.        ,   236.1516035 ,
        2066.32653061])

In [55]:
np.prod(v2, axis=0) # finds product of all items row wise in numpy array

array([-12650.97875885,      0.        ,  12650.97875885])

In [56]:
v2.T

array([[-15.        ,  -8.57142857,  -2.14285714,   4.28571429,
         10.71428571],
       [-12.85714286,  -6.42857143,   0.        ,   6.42857143,
         12.85714286],
       [-10.71428571,  -4.28571429,   2.14285714,   8.57142857,
         15.        ]])

In [58]:
np.ravel(v2)

array([-15.        , -12.85714286, -10.71428571,  -8.57142857,
        -6.42857143,  -4.28571429,  -2.14285714,   0.        ,
         2.14285714,   4.28571429,   6.42857143,   8.57142857,
        10.71428571,  12.85714286,  15.        ])